#!/usr/bin/env ruby
# frozen_string_literal: true

#
# This is in a poor location. The work to move this under bin/ is ongoing and
# will be completed in cucumber-rails v3
#
# https://github.com/cucumber/cucumber-rails/issues/438
#

vendored_cucumber_bin = Dir["#{File.dirname(__FILE__)}/../vendor/{gems,plugins}/cucumber*/bin/cucumber"].first
if vendored_cucumber_bin
  load File.expand_path(vendored_cucumber_bin)
else
  require "rubygems" unless ENV["NO_RUBYGEMS"]
  require "cucumber"
  load Cucumber::BINARY
end
